### ISSUE TITLE
Dates are not advancing

### ISSUE THREAD

**Issue by lawndartgoalie** [katzwebservices/Wunderground#28]
Love your plugin, very easy to configure with short code. 

Unfortunately the date does not advance automatically my two sites are stuck on the date from when I  reinstalled the plugin. 

assumptiongranger.org - is one of the sites. 

I am running cron job through c-panel and disabled WP cron in wp-config.php - Is it possible that is the problem?

Thanks,
Shannon

**Comment by cledi** [comment]
Same here...

**Comment by cledi** [comment]
wpc open weather is a good alternative, I just changed...

**Comment by crunnells** [comment]
FYI -- This is probably a WordPress transients issue. Download a plugin to manage your transients (like https://wordpress.org/plugins/artiss-transient-cleaner/) and delete them all (back up your database first). I had the same problem where the date was stuck in October, and deleting the transients fixed the problem. Not sure what causes transients to get stuck, but I've seen it on a few sites now.

**Comment by zackkatz** [comment]
This is fixed in #47 - the issue was likely using Personal Weather Station data, which is not reliable.
