### ISSUE TITLE
Weather forecast is not pulling the same info as the wunderground.com website

### ISSUE THREAD

**Issue by mbbdesign** [katzwebservices/Wunderground#30]
The test site is here:
https://test.ratliffreadymix.com

Waco, Texas forecast:
http://www.wunderground.com/q/zmw:76799.1.99999?sp=KTXWACO12&MR=1

The info is being pulled into the site is shows Waco, Texas but the forecast and current conditions are not the same as what you’ll find on the Weather Underground website.

The home page is utilizing the shortcode and the employee page (footer navigation) is using the widget. Both display incorrect information.

**Comment by mbbdesign** [comment]
I changed the shortcode to use the Wunderground "zmw" and it now matches the data on the wunderground website. But, it is now stuck on Sat (two days ago from this post) and will not refresh. Any help in appreciated?

**Comment by zackkatz** [comment]
It's likely you're using a Personal Weather Station ZMW. Please see #36
