### ISSUE TITLE
How to prevent loading stylesheet?

### ISSUE THREAD

**Issue by draney** [katzwebservices/Wunderground#33]
I have added the CSS to my stylesheet and would like to turn off the WU stylesheet.
I've tried adding both of these to my functions.php:
     wp_dequeue_style( 'wunderground' );
     wp_deregister_style( 'wunderground' );

**Comment by zackkatz** [comment]
Try this instead: 

```
add_action('wunderground_print_scripts', 'dequeue_wunderground_style', 11 );
add_action('wp_enqueue_scripts', 'dequeue_wunderground_style', 11 );
function dequeue_wunderground_style() {
    wp_dequeue_style('wunderground');
}
```
