### ISSUE TITLE
High / Low not translated to dutch

### ISSUE THREAD

**Issue by MichaelRosmane** [katzwebservices/Wunderground#35]
I'm using your plugin on a clients website, and everything translates nicely into dutch, except for the high & low temperature strings. 

I'm using the shortcode with the language var set to NL.

I've already looked at the template files but I can't seem to find a way to translate them without editing the plugin core files. 

I've attached a screenshot to illustratue the issue. 

Edit: I'd be happy to supply the translations if needed. 

![image](https://cloud.githubusercontent.com/assets/8267293/11392947/2a112a04-935d-11e5-986a-80aceae2b3d9.png)

**Comment by zackkatz** [comment]
You can update the translations here: https://translate.wordpress.org/projects/wp-plugins/wunderground

Thanks!
