### ISSUE TITLE
error fetching the forecast: invalidkey

### ISSUE THREAD

**Issue by WhatcomMktg** [katzwebservices/Wunderground#43]
The WordPress widget, which has been performing brilliantly for months, now today displays "error fetching the forecast: invalidkey" and the 'forecast' shortcode, which also has been brilliant, now displays "The location could not be found."

Temporary issue or ???

**Comment by zackkatz** [comment]
The API key has been disabled; I'm contacting Weather Underground for more information. Hopefully this will be fixed tomorrow.

**Comment by zackkatz** [comment]
They have updated the API key to be active again; this issue is fixed. Sorry for the inconvenience!
