### ISSUE TITLE
WeatherUnderground WordPress Plugin Abandoned

### ISSUE THREAD

**Issue by heilincoo** [katzwebservices/Wunderground#65]
We use the Weather Underground plugin on our WordPress plugin.
We are quite happy with this plugin.  However, it hasn't been updated for over 2 years.
Word Press is warning that it hasn't been tested with newest version of WP.

We do try to keep our plugins up to date but I do like to use up-to-date plugins.
Would it be possible for you to take a look at this issue.  Thanks much.
![weatherundergroundissue](https://user-images.githubusercontent.com/41006500/42453229-13ec0fe2-835a-11e8-9ea0-bc83788e25d9.JPG)

**Comment by jasonbronson** [comment]
https://www.wunderground.com/weather/api/ The original site has shutdown access.

**Comment by heilincoo** [comment]
The plugin seems to be working at this time.
